/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD$
 */

#define	V7_SYS_v7_nosys	0
#define	V7_SYS_v7_exit	1
#define	V7_SYS_v7_fork	2
#define	V7_SYS_v7_read	3
#define	V7_SYS_v7_write	4
#define	V7_SYS_v7_open	5
#define	V7_SYS_v7_close	6
#define	V7_SYS_v7_wait	7
#define	V7_SYS_v7_creat	8
#define	V7_SYS_v7_link	9
#define	V7_SYS_v7_unlink	10
#define	V7_SYS_v7_execv	11
#define	V7_SYS_v7_chdir	12
#define	V7_SYS_v7_time	13
#define	V7_SYS_v7_mknod	14
#define	V7_SYS_v7_chmod	15
#define	V7_SYS_v7_chown	16
#define	V7_SYS_v7_break	17
#define	V7_SYS_v7_stat	18
#define	V7_SYS_v7_lseek	19
#define	V7_SYS_v7_getpid	20
#define	V7_SYS_v7_mount	21
#define	V7_SYS_v7_umount	22
#define	V7_SYS_v7_setuid	23
#define	V7_SYS_v7_getuid	24
#define	V7_SYS_v7_stime	25
#define	V7_SYS_v7_ptrace	26
#define	V7_SYS_v7_alarm	27
#define	V7_SYS_v7_fstat	28
#define	V7_SYS_v7_pause	29
#define	V7_SYS_v7_utime	30
#define	V7_SYS_v7_access	33
#define	V7_SYS_v7_nice	34
#define	V7_SYS_v7_sync	36
#define	V7_SYS_v7_kill	37
#define	V7_SYS_v7_dup	41
#define	V7_SYS_v7_pipe	42
#define	V7_SYS_v7_times	43
#define	V7_SYS_v7_profil	44
#define	V7_SYS_v7_setgid	46
#define	V7_SYS_v7_getgid	47
#define	V7_SYS_v7_sigsys	48
#define	V7_SYS_v7_ioctl	54
#define	V7_SYS_v7_execve	59
#define	V7_SYS_umask	60
#define	V7_SYS_chroot	61
#define	V7_SYS_MAXSYSCALL	64
