/*
 * System call argument to DTrace register array converstion.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD$
 * This file is part of the DTrace syscall provider.
 */

static void
systrace_args(int sysnum, void *params, uint64_t *uarg, int *n_args)
{
	int64_t *iarg  = (int64_t *) uarg;
	switch (sysnum) {
	/* v7_nosys */
	case 0: {
		*n_args = 0;
		break;
	}
	/* v7_exit */
	case 1: {
		struct v7_exit_args *p = params;
		iarg[0] = p->rval; /* int */
		*n_args = 1;
		break;
	}
	/* v7_fork */
	case 2: {
		*n_args = 0;
		break;
	}
	/* v7_read */
	case 3: {
		struct v7_read_args *p = params;
		iarg[0] = p->fd; /* int */
		uarg[1] = (intptr_t) p->buf; /* char * */
		uarg[2] = p->nbytes; /* u_int */
		*n_args = 3;
		break;
	}
	/* v7_write */
	case 4: {
		struct v7_write_args *p = params;
		iarg[0] = p->fd; /* int */
		uarg[1] = (intptr_t) p->buf; /* char * */
		uarg[2] = p->nbytes; /* u_int */
		*n_args = 3;
		break;
	}
	/* v7_open */
	case 5: {
		struct v7_open_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		iarg[1] = p->flags; /* int */
		iarg[2] = p->mode; /* int */
		*n_args = 3;
		break;
	}
	/* v7_close */
	case 6: {
		struct v7_close_args *p = params;
		iarg[0] = p->fd; /* int */
		*n_args = 1;
		break;
	}
	/* v7_wait */
	case 7: {
		struct v7_wait_args *p = params;
		iarg[0] = p->a1; /* int */
		iarg[1] = p->a2; /* int */
		iarg[2] = p->a3; /* int */
		*n_args = 3;
		break;
	}
	/* v7_creat */
	case 8: {
		struct v7_creat_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		iarg[1] = p->mode; /* int */
		*n_args = 2;
		break;
	}
	/* v7_link */
	case 9: {
		struct v7_link_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		uarg[1] = (intptr_t) p->link; /* char * */
		*n_args = 2;
		break;
	}
	/* v7_unlink */
	case 10: {
		struct v7_unlink_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		*n_args = 1;
		break;
	}
	/* v7_execv */
	case 11: {
		struct v7_execv_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		uarg[1] = (intptr_t) p->argp; /* char ** */
		*n_args = 2;
		break;
	}
	/* v7_chdir */
	case 12: {
		struct v7_chdir_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		*n_args = 1;
		break;
	}
	/* v7_time */
	case 13: {
		struct v7_time_args *p = params;
		uarg[0] = (intptr_t) p->tp; /* v7_time_t * */
		*n_args = 1;
		break;
	}
	/* v7_mknod */
	case 14: {
		struct v7_mknod_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		iarg[1] = p->mode; /* int */
		iarg[2] = p->dev; /* int */
		*n_args = 3;
		break;
	}
	/* v7_chmod */
	case 15: {
		struct v7_chmod_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		iarg[1] = p->mode; /* int */
		*n_args = 2;
		break;
	}
	/* v7_chown */
	case 16: {
		struct v7_chown_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		iarg[1] = p->uid; /* int */
		iarg[2] = p->gid; /* int */
		*n_args = 3;
		break;
	}
	/* v7_break */
	case 17: {
		struct v7_break_args *p = params;
		uarg[0] = (intptr_t) p->nsize; /* caddr_t */
		*n_args = 1;
		break;
	}
	/* v7_stat */
	case 18: {
		struct v7_stat_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		uarg[1] = (intptr_t) p->st; /* struct v7_stat * */
		*n_args = 2;
		break;
	}
	/* v7_lseek */
	case 19: {
		struct v7_lseek_args *p = params;
		iarg[0] = p->fd; /* int */
		iarg[1] = p->offset; /* long */
		iarg[2] = p->whence; /* int */
		*n_args = 3;
		break;
	}
	/* v7_getpid */
	case 20: {
		*n_args = 0;
		break;
	}
	/* v7_mount */
	case 21: {
		struct v7_mount_args *p = params;
		uarg[0] = (intptr_t) p->special; /* char * */
		uarg[1] = (intptr_t) p->dir; /* char * */
		iarg[2] = p->flags; /* int */
		iarg[3] = p->fstype; /* int */
		uarg[4] = (intptr_t) p->data; /* char * */
		iarg[5] = p->len; /* int */
		*n_args = 6;
		break;
	}
	/* v7_umount */
	case 22: {
		struct v7_umount_args *p = params;
		uarg[0] = (intptr_t) p->name; /* char * */
		*n_args = 1;
		break;
	}
	/* v7_setuid */
	case 23: {
		struct v7_setuid_args *p = params;
		iarg[0] = p->uid; /* int */
		*n_args = 1;
		break;
	}
	/* v7_getuid */
	case 24: {
		*n_args = 0;
		break;
	}
	/* v7_stime */
	case 25: {
		struct v7_stime_args *p = params;
		uarg[0] = (intptr_t) p->timep; /* long * */
		*n_args = 1;
		break;
	}
	/* v7_ptrace */
	case 26: {
		struct v7_ptrace_args *p = params;
		iarg[0] = p->req; /* int */
		iarg[1] = p->pid; /* pid_t */
		uarg[2] = (intptr_t) p->addr; /* caddr_t */
		iarg[3] = p->data; /* int */
		*n_args = 4;
		break;
	}
	/* v7_alarm */
	case 27: {
		struct v7_alarm_args *p = params;
		uarg[0] = p->sec; /* unsigned */
		*n_args = 1;
		break;
	}
	/* v7_fstat */
	case 28: {
		struct v7_fstat_args *p = params;
		iarg[0] = p->fd; /* int */
		uarg[1] = (intptr_t) p->st; /* struct v7_stat * */
		*n_args = 2;
		break;
	}
	/* v7_pause */
	case 29: {
		*n_args = 0;
		break;
	}
	/* v7_utime */
	case 30: {
		struct v7_utime_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		uarg[1] = (intptr_t) p->buf; /* struct v7_utimbuf * */
		*n_args = 2;
		break;
	}
	/* v7_access */
	case 33: {
		struct v7_access_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		iarg[1] = p->amode; /* int */
		*n_args = 2;
		break;
	}
	/* v7_nice */
	case 34: {
		struct v7_nice_args *p = params;
		iarg[0] = p->incr; /* int */
		*n_args = 1;
		break;
	}
	/* v7_sync */
	case 36: {
		*n_args = 0;
		break;
	}
	/* v7_kill */
	case 37: {
		struct v7_kill_args *p = params;
		iarg[0] = p->pid; /* int */
		iarg[1] = p->signo; /* int */
		*n_args = 2;
		break;
	}
	/* v7_dup */
	case 41: {
		struct v7_dup_args *p = params;
		uarg[0] = p->fd; /* u_int */
		*n_args = 1;
		break;
	}
	/* v7_pipe */
	case 42: {
		*n_args = 0;
		break;
	}
	/* v7_times */
	case 43: {
		struct v7_times_args *p = params;
		uarg[0] = (intptr_t) p->tp; /* struct tms * */
		*n_args = 1;
		break;
	}
	/* v7_profil */
	case 44: {
		struct v7_profil_args *p = params;
		uarg[0] = (intptr_t) p->samples; /* caddr_t */
		uarg[1] = p->size; /* u_int */
		uarg[2] = p->offset; /* u_int */
		uarg[3] = p->scale; /* u_int */
		*n_args = 4;
		break;
	}
	/* v7_setgid */
	case 46: {
		struct v7_setgid_args *p = params;
		iarg[0] = p->gid; /* int */
		*n_args = 1;
		break;
	}
	/* v7_getgid */
	case 47: {
		*n_args = 0;
		break;
	}
	/* v7_sigsys */
	case 48: {
		struct v7_sigsys_args *p = params;
		iarg[0] = p->sig; /* int */
		iarg[1] = p->fp; /* v7_sig_t */
		*n_args = 2;
		break;
	}
	/* v7_ioctl */
	case 54: {
		struct v7_ioctl_args *p = params;
		iarg[0] = p->fd; /* int */
		iarg[1] = p->cmd; /* int */
		uarg[2] = (intptr_t) p->data; /* caddr_t */
		*n_args = 3;
		break;
	}
	/* v7_execve */
	case 59: {
		struct v7_execve_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		uarg[1] = (intptr_t) p->argp; /* char ** */
		uarg[2] = (intptr_t) p->envp; /* char ** */
		*n_args = 3;
		break;
	}
	/* umask */
	case 60: {
		struct umask_args *p = params;
		iarg[0] = p->newmask; /* int */
		*n_args = 1;
		break;
	}
	/* chroot */
	case 61: {
		struct chroot_args *p = params;
		uarg[0] = (intptr_t) p->path; /* char * */
		*n_args = 1;
		break;
	}
	default:
		*n_args = 0;
		break;
	};
}
static void
systrace_entry_setargdesc(int sysnum, int ndx, char *desc, size_t descsz)
{
	const char *p = NULL;
	switch (sysnum) {
	/* v7_nosys */
	case 0:
		break;
	/* v7_exit */
	case 1:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_fork */
	case 2:
		break;
	/* v7_read */
	case 3:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "userland char *";
			break;
		case 2:
			p = "u_int";
			break;
		default:
			break;
		};
		break;
	/* v7_write */
	case 4:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "userland char *";
			break;
		case 2:
			p = "u_int";
			break;
		default:
			break;
		};
		break;
	/* v7_open */
	case 5:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "int";
			break;
		case 2:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_close */
	case 6:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_wait */
	case 7:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "int";
			break;
		case 2:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_creat */
	case 8:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_link */
	case 9:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "userland char *";
			break;
		default:
			break;
		};
		break;
	/* v7_unlink */
	case 10:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		default:
			break;
		};
		break;
	/* v7_execv */
	case 11:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "userland char **";
			break;
		default:
			break;
		};
		break;
	/* v7_chdir */
	case 12:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		default:
			break;
		};
		break;
	/* v7_time */
	case 13:
		switch(ndx) {
		case 0:
			p = "userland v7_time_t *";
			break;
		default:
			break;
		};
		break;
	/* v7_mknod */
	case 14:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "int";
			break;
		case 2:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_chmod */
	case 15:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_chown */
	case 16:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "int";
			break;
		case 2:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_break */
	case 17:
		switch(ndx) {
		case 0:
			p = "caddr_t";
			break;
		default:
			break;
		};
		break;
	/* v7_stat */
	case 18:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "userland struct v7_stat *";
			break;
		default:
			break;
		};
		break;
	/* v7_lseek */
	case 19:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "long";
			break;
		case 2:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_getpid */
	case 20:
		break;
	/* v7_mount */
	case 21:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "userland char *";
			break;
		case 2:
			p = "int";
			break;
		case 3:
			p = "int";
			break;
		case 4:
			p = "userland char *";
			break;
		case 5:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_umount */
	case 22:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		default:
			break;
		};
		break;
	/* v7_setuid */
	case 23:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_getuid */
	case 24:
		break;
	/* v7_stime */
	case 25:
		switch(ndx) {
		case 0:
			p = "userland long *";
			break;
		default:
			break;
		};
		break;
	/* v7_ptrace */
	case 26:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "pid_t";
			break;
		case 2:
			p = "caddr_t";
			break;
		case 3:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_alarm */
	case 27:
		switch(ndx) {
		case 0:
			p = "unsigned";
			break;
		default:
			break;
		};
		break;
	/* v7_fstat */
	case 28:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "userland struct v7_stat *";
			break;
		default:
			break;
		};
		break;
	/* v7_pause */
	case 29:
		break;
	/* v7_utime */
	case 30:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "userland struct v7_utimbuf *";
			break;
		default:
			break;
		};
		break;
	/* v7_access */
	case 33:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_nice */
	case 34:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_sync */
	case 36:
		break;
	/* v7_kill */
	case 37:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_dup */
	case 41:
		switch(ndx) {
		case 0:
			p = "u_int";
			break;
		default:
			break;
		};
		break;
	/* v7_pipe */
	case 42:
		break;
	/* v7_times */
	case 43:
		switch(ndx) {
		case 0:
			p = "userland struct tms *";
			break;
		default:
			break;
		};
		break;
	/* v7_profil */
	case 44:
		switch(ndx) {
		case 0:
			p = "caddr_t";
			break;
		case 1:
			p = "u_int";
			break;
		case 2:
			p = "u_int";
			break;
		case 3:
			p = "u_int";
			break;
		default:
			break;
		};
		break;
	/* v7_setgid */
	case 46:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* v7_getgid */
	case 47:
		break;
	/* v7_sigsys */
	case 48:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "v7_sig_t";
			break;
		default:
			break;
		};
		break;
	/* v7_ioctl */
	case 54:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		case 1:
			p = "int";
			break;
		case 2:
			p = "caddr_t";
			break;
		default:
			break;
		};
		break;
	/* v7_execve */
	case 59:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		case 1:
			p = "userland char **";
			break;
		case 2:
			p = "userland char **";
			break;
		default:
			break;
		};
		break;
	/* umask */
	case 60:
		switch(ndx) {
		case 0:
			p = "int";
			break;
		default:
			break;
		};
		break;
	/* chroot */
	case 61:
		switch(ndx) {
		case 0:
			p = "userland char *";
			break;
		default:
			break;
		};
		break;
	default:
		break;
	};
	if (p != NULL)
		strlcpy(desc, p, descsz);
}
static void
systrace_return_setargdesc(int sysnum, int ndx, char *desc, size_t descsz)
{
	const char *p = NULL;
	switch (sysnum) {
	/* v7_nosys */
	case 0:
	/* v7_exit */
	case 1:
		if (ndx == 0 || ndx == 1)
			p = "void";
		break;
	/* v7_fork */
	case 2:
	/* v7_read */
	case 3:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_write */
	case 4:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_open */
	case 5:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_close */
	case 6:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_wait */
	case 7:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_creat */
	case 8:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_link */
	case 9:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_unlink */
	case 10:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_execv */
	case 11:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_chdir */
	case 12:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_time */
	case 13:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_mknod */
	case 14:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_chmod */
	case 15:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_chown */
	case 16:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_break */
	case 17:
		if (ndx == 0 || ndx == 1)
			p = "caddr_t";
		break;
	/* v7_stat */
	case 18:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_lseek */
	case 19:
		if (ndx == 0 || ndx == 1)
			p = "long";
		break;
	/* v7_getpid */
	case 20:
	/* v7_mount */
	case 21:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_umount */
	case 22:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_setuid */
	case 23:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_getuid */
	case 24:
	/* v7_stime */
	case 25:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_ptrace */
	case 26:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_alarm */
	case 27:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_fstat */
	case 28:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_pause */
	case 29:
	/* v7_utime */
	case 30:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_access */
	case 33:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_nice */
	case 34:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_sync */
	case 36:
	/* v7_kill */
	case 37:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_dup */
	case 41:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_pipe */
	case 42:
	/* v7_times */
	case 43:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_profil */
	case 44:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_setgid */
	case 46:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_getgid */
	case 47:
	/* v7_sigsys */
	case 48:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_ioctl */
	case 54:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* v7_execve */
	case 59:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* umask */
	case 60:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	/* chroot */
	case 61:
		if (ndx == 0 || ndx == 1)
			p = "int";
		break;
	default:
		break;
	};
	if (p != NULL)
		strlcpy(desc, p, descsz);
}
