/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD$
 */

#include <sys/param.h>
#include <sys/sysent.h>
#include <sys/sysproto.h>
#include <compat/v7/v7_type.h>
#include <compat/v7/v7_signal.h>
#include <compat/v7/v7_proto.h>

#define AS(name) (sizeof(struct name) / sizeof(register_t))

/* The casts are bogus but will do for now. */
struct sysent v7_sysent[] = {
	{ 0, (sy_call_t *)sys_v7_nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 0 = v7_nosys */
	{ AS(v7_exit_args), (sy_call_t *)sys_v7_exit, AUE_EXIT, NULL, 0, 0, 0, SY_THR_STATIC },	/* 1 = v7_exit */
	{ 0, (sy_call_t *)sys_v7_fork, AUE_FORK, NULL, 0, 0, 0, SY_THR_STATIC },	/* 2 = v7_fork */
	{ AS(v7_read_args), (sy_call_t *)sys_v7_read, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 3 = v7_read */
	{ AS(v7_write_args), (sy_call_t *)sys_v7_write, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 4 = v7_write */
	{ AS(v7_open_args), (sy_call_t *)sys_v7_open, AUE_OPEN_RWTC, NULL, 0, 0, 0, SY_THR_STATIC },	/* 5 = v7_open */
	{ AS(v7_close_args), (sy_call_t *)sys_v7_close, AUE_CLOSE, NULL, 0, 0, 0, SY_THR_STATIC },	/* 6 = v7_close */
	{ AS(v7_wait_args), (sy_call_t *)sys_v7_wait, AUE_WAIT4, NULL, 0, 0, 0, SY_THR_STATIC },	/* 7 = v7_wait */
	{ AS(v7_creat_args), (sy_call_t *)sys_v7_creat, AUE_CREAT, NULL, 0, 0, 0, SY_THR_STATIC },	/* 8 = v7_creat */
	{ AS(v7_link_args), (sy_call_t *)sys_v7_link, AUE_LINK, NULL, 0, 0, 0, SY_THR_STATIC },	/* 9 = v7_link */
	{ AS(v7_unlink_args), (sy_call_t *)sys_v7_unlink, AUE_UNLINK, NULL, 0, 0, 0, SY_THR_STATIC },	/* 10 = v7_unlink */
	{ AS(v7_execv_args), (sy_call_t *)sys_v7_execv, AUE_EXECVE, NULL, 0, 0, 0, SY_THR_STATIC },	/* 11 = v7_execv */
	{ AS(v7_chdir_args), (sy_call_t *)sys_v7_chdir, AUE_CHDIR, NULL, 0, 0, 0, SY_THR_STATIC },	/* 12 = v7_chdir */
	{ AS(v7_time_args), (sy_call_t *)sys_v7_time, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 13 = v7_time */
	{ AS(v7_mknod_args), (sy_call_t *)sys_v7_mknod, AUE_MKNOD, NULL, 0, 0, 0, SY_THR_STATIC },	/* 14 = v7_mknod */
	{ AS(v7_chmod_args), (sy_call_t *)sys_v7_chmod, AUE_CHMOD, NULL, 0, 0, 0, SY_THR_STATIC },	/* 15 = v7_chmod */
	{ AS(v7_chown_args), (sy_call_t *)sys_v7_chown, AUE_CHOWN, NULL, 0, 0, 0, SY_THR_STATIC },	/* 16 = v7_chown */
	{ AS(v7_break_args), (sy_call_t *)sys_v7_break, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 17 = v7_break */
	{ AS(v7_stat_args), (sy_call_t *)sys_v7_stat, AUE_STAT, NULL, 0, 0, 0, SY_THR_STATIC },	/* 18 = v7_stat */
	{ AS(v7_lseek_args), (sy_call_t *)sys_v7_lseek, AUE_LSEEK, NULL, 0, 0, 0, SY_THR_STATIC },	/* 19 = v7_lseek */
	{ 0, (sy_call_t *)sys_v7_getpid, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 20 = v7_getpid */
	{ AS(v7_mount_args), (sy_call_t *)sys_v7_mount, AUE_MOUNT, NULL, 0, 0, 0, SY_THR_STATIC },	/* 21 = v7_mount */
	{ AS(v7_umount_args), (sy_call_t *)sys_v7_umount, AUE_UMOUNT, NULL, 0, 0, 0, SY_THR_STATIC },	/* 22 = v7_umount */
	{ AS(v7_setuid_args), (sy_call_t *)sys_v7_setuid, AUE_SETUID, NULL, 0, 0, 0, SY_THR_STATIC },	/* 23 = v7_setuid */
	{ 0, (sy_call_t *)sys_v7_getuid, AUE_GETUID, NULL, 0, 0, 0, SY_THR_STATIC },	/* 24 = v7_getuid */
	{ AS(v7_stime_args), (sy_call_t *)sys_v7_stime, AUE_SETTIMEOFDAY, NULL, 0, 0, 0, SY_THR_STATIC },	/* 25 = v7_stime */
	{ AS(v7_ptrace_args), (sy_call_t *)sys_v7_ptrace, AUE_PTRACE, NULL, 0, 0, 0, SY_THR_STATIC },	/* 26 = v7_ptrace */
	{ AS(v7_alarm_args), (sy_call_t *)sys_v7_alarm, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 27 = v7_alarm */
	{ AS(v7_fstat_args), (sy_call_t *)sys_v7_fstat, AUE_FSTAT, NULL, 0, 0, 0, SY_THR_STATIC },	/* 28 = v7_fstat */
	{ 0, (sy_call_t *)sys_v7_pause, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 29 = v7_pause */
	{ AS(v7_utime_args), (sy_call_t *)sys_v7_utime, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 30 = v7_utime */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 31 = v7_stty */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 32 = v7_gtty */
	{ AS(v7_access_args), (sy_call_t *)sys_v7_access, AUE_ACCESS, NULL, 0, 0, 0, SY_THR_STATIC },	/* 33 = v7_access */
	{ AS(v7_nice_args), (sy_call_t *)sys_v7_nice, AUE_NICE, NULL, 0, 0, 0, SY_THR_STATIC },	/* 34 = v7_nice */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 35 = v7_ftime */
	{ 0, (sy_call_t *)sys_v7_sync, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 36 = v7_sync */
	{ AS(v7_kill_args), (sy_call_t *)sys_v7_kill, AUE_KILL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 37 = v7_kill */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 38 = v7_switch */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 39 = v7_setpgrp */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 40 = v7_tell */
	{ AS(v7_dup_args), (sy_call_t *)sys_v7_dup, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 41 = v7_dup */
	{ 0, (sy_call_t *)sys_v7_pipe, AUE_PIPE, NULL, 0, 0, 0, SY_THR_STATIC },	/* 42 = v7_pipe */
	{ AS(v7_times_args), (sy_call_t *)sys_v7_times, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 43 = v7_times */
	{ AS(v7_profil_args), (sy_call_t *)sys_v7_profil, AUE_PROFILE, NULL, 0, 0, 0, SY_THR_STATIC },	/* 44 = v7_profil */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 45 = v7_unused */
	{ AS(v7_setgid_args), (sy_call_t *)sys_v7_setgid, AUE_SETGID, NULL, 0, 0, 0, SY_THR_STATIC },	/* 46 = v7_setgid */
	{ 0, (sy_call_t *)sys_v7_getgid, AUE_GETGID, NULL, 0, 0, 0, SY_THR_STATIC },	/* 47 = v7_getgid */
	{ AS(v7_sigsys_args), (sy_call_t *)sys_v7_sigsys, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 48 = v7_sigsys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 49 = v7_unused */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 50 = v7_unused */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 51 = v7_acct */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 52 = v7_sysphys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 53 = v7_syslock */
	{ AS(v7_ioctl_args), (sy_call_t *)sys_v7_ioctl, AUE_IOCTL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 54 = v7_ioctl */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 55 = v7_readwrite */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 56 = v7_mpxchan */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 57 = v7_reserved */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 58 = v7_reserved */
	{ AS(v7_execve_args), (sy_call_t *)sys_v7_execve, AUE_EXECVE, NULL, 0, 0, 0, SY_THR_STATIC },	/* 59 = v7_execve */
	{ AS(umask_args), (sy_call_t *)sys_umask, AUE_UMASK, NULL, 0, 0, 0, SY_THR_STATIC },	/* 60 = umask */
	{ AS(chroot_args), (sy_call_t *)sys_chroot, AUE_CHROOT, NULL, 0, 0, 0, SY_THR_STATIC },	/* 61 = chroot */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 62 = v7_reserved */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 63 = v7_reserved */
};
