/*
 * System call names.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD$
 */

const char *v7_syscallnames[] = {
	"v7_nosys",			/* 0 = v7_nosys */
	"v7_exit",			/* 1 = v7_exit */
	"v7_fork",			/* 2 = v7_fork */
	"v7_read",			/* 3 = v7_read */
	"v7_write",			/* 4 = v7_write */
	"v7_open",			/* 5 = v7_open */
	"v7_close",			/* 6 = v7_close */
	"v7_wait",			/* 7 = v7_wait */
	"v7_creat",			/* 8 = v7_creat */
	"v7_link",			/* 9 = v7_link */
	"v7_unlink",			/* 10 = v7_unlink */
	"v7_execv",			/* 11 = v7_execv */
	"v7_chdir",			/* 12 = v7_chdir */
	"v7_time",			/* 13 = v7_time */
	"v7_mknod",			/* 14 = v7_mknod */
	"v7_chmod",			/* 15 = v7_chmod */
	"v7_chown",			/* 16 = v7_chown */
	"v7_break",			/* 17 = v7_break */
	"v7_stat",			/* 18 = v7_stat */
	"v7_lseek",			/* 19 = v7_lseek */
	"v7_getpid",			/* 20 = v7_getpid */
	"v7_mount",			/* 21 = v7_mount */
	"v7_umount",			/* 22 = v7_umount */
	"v7_setuid",			/* 23 = v7_setuid */
	"v7_getuid",			/* 24 = v7_getuid */
	"v7_stime",			/* 25 = v7_stime */
	"v7_ptrace",			/* 26 = v7_ptrace */
	"v7_alarm",			/* 27 = v7_alarm */
	"v7_fstat",			/* 28 = v7_fstat */
	"v7_pause",			/* 29 = v7_pause */
	"v7_utime",			/* 30 = v7_utime */
	"#31",			/* 31 = v7_stty */
	"#32",			/* 32 = v7_gtty */
	"v7_access",			/* 33 = v7_access */
	"v7_nice",			/* 34 = v7_nice */
	"#35",			/* 35 = v7_ftime */
	"v7_sync",			/* 36 = v7_sync */
	"v7_kill",			/* 37 = v7_kill */
	"#38",			/* 38 = v7_switch */
	"#39",			/* 39 = v7_setpgrp */
	"#40",			/* 40 = v7_tell */
	"v7_dup",			/* 41 = v7_dup */
	"v7_pipe",			/* 42 = v7_pipe */
	"v7_times",			/* 43 = v7_times */
	"v7_profil",			/* 44 = v7_profil */
	"#45",			/* 45 = v7_unused */
	"v7_setgid",			/* 46 = v7_setgid */
	"v7_getgid",			/* 47 = v7_getgid */
	"v7_sigsys",			/* 48 = v7_sigsys */
	"#49",			/* 49 = v7_unused */
	"#50",			/* 50 = v7_unused */
	"#51",			/* 51 = v7_acct */
	"#52",			/* 52 = v7_sysphys */
	"#53",			/* 53 = v7_syslock */
	"v7_ioctl",			/* 54 = v7_ioctl */
	"#55",			/* 55 = v7_readwrite */
	"#56",			/* 56 = v7_mpxchan */
	"#57",			/* 57 = v7_reserved */
	"#58",			/* 58 = v7_reserved */
	"v7_execve",			/* 59 = v7_execve */
	"umask",			/* 60 = umask */
	"chroot",			/* 61 = chroot */
	"#62",			/* 62 = v7_reserved */
	"#63",			/* 63 = v7_reserved */
};
