.\" Copyright (c) 2023 Netflix, Inc
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd June 10, 2023
.Dt CAM_CCB 9
.Os
.Nm cam_ccb
.Nd "CAM Control Blocks"
.Sh DESCRIPTION
CAM control blocks (CCBs) pass messages between periph drivers and the lower
layers of CAM.
.Sh BUGS
All the details about CCBs are documented only in the code today.
