.\" Copyright (c) 2023 Netflix, Inc
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd June 10, 2023
.Dt CAM_SIM 9
.Os
.Nm cam_sim
.Nd "CAM System Interface Module"
.Sh DESCRIPTION
The CAM system interface module (SIM) accepts CCBs from the upper layers and
translates them into hardware dependent transactions.
.Sh BUGS
All the details about SIM are documented only in the code today.
