.\" Copyright (c) 2023 Netflix, Inc
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd June 10, 2023
.Dt CAM_XPT 9
.Os
.Nm cam_xpt
.Nd "CAM Transport Layer"
.Sh DESCRIPTION
The CAM trnasport layer (XPT) marhsals messages in CCBs between the periph
drivers and, where necessary, the SIM.
.Sh BUGS
All the details about XPT are documented only in the code today.
